trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  dotnetVersion: '8.0.x'

steps:
- task: UseDotNet@2
  inputs:
    packageType: sdk
    version: $(dotnetVersion)

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: restore
    projects: '**/*.sln'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: build
    projects: '**/*.sln'
    arguments: '--configuration $(buildConfiguration)'

# ✅ Add this test step
- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests'
  inputs:
    command: test
    projects: '**/*Application.Tests.csproj'
    arguments: '--configuration $(buildConfiguration) --no-build'

# If tests fail, pipeline stops here—no publish, no deploy

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: publish
    projects: 'Server/Server.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1'
    appName: 'heroprofile'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
